service: our-family-photos

image: rjnawara/our-family-photos

servers:
  web:
    hosts:
      - 45.159.231.79

registry:
  username: rjnawara
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    HOSTNAME: our-family-photos.raynawara.com
    RAILS_SERVE_STATIC_FILES: true
    RAILS_LOG_TO_STDOUT: true
  secret:
    - CLOUDFLARE_ACCOUNT_ID
    - CLOUDFLARE_ACCESS_KEY_ID
    - CLOUDFLARE_SECRET_ACCESS_KEY
    - KAMAL_REGISTRY_PASSWORD
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

builder:
  arch: amd64

proxy:
  host: our-family-photos.raynawara.com
  app_port: 3000
  ssl: true
